version: '3.8'

services:
  # --- 1. BANCO DE DADOS (PostgreSQL)
  database:
    image: postgres:15-alpine
    container_name: sgd-postgres-v1 
    environment:
      POSTGRES_USER: srv_discografia
      POSTGRES_PASSWORD: P@ssw0rd_Seplag2026!
      POSTGRES_DB: db_discografia_core
    ports:
      - "5432:5432"
    volumes:
      - pg_discografia_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U srv_discografia -d db_discografia_core"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sgd-network

  # --- 2. BACKEND (Spring Boot)
  backend:
    build: ./backend
    container_name: sgd-backend-v1
    ports:
      - "3333:3333"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db_discografia_core
      SPRING_DATASOURCE_USERNAME: srv_discografia
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd_Seplag2026!
      APP_MINIO_URL: http://storage:9000
      APP_MINIO_ACCESS-KEY: admin_storage
      APP_MINIO_SECRET-KEY: Storage_Key_2026!
    depends_on:
      database:
        condition: service_healthy
      storage:
        condition: service_started
    networks:
      - sgd-network

  # --- 3. OBJECT STORAGE (MinIO)
  storage:
    image: minio/minio:latest
    container_name: sgd-minio-v1
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin_storage
      MINIO_ROOT_PASSWORD: Storage_Key_2026!
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage_data:/data
    networks:
      - sgd-network

  # --- 4. CONFIGURAÇÃO AUTOMÁTICA STORAGE
  storage-setup:
    image: minio/mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set sgd-local http://storage:9000 admin_storage Storage_Key_2026!; do echo '...aguardando MinIO...'; sleep 1; done;
      /usr/bin/mc mb --ignore-existing sgd-local/capas-albuns-media;
      /usr/bin/mc anonymous set public sgd-local/capas-albuns-media;
      exit 0;
      "
    networks:
      - sgd-network 
  # --- 5. FRONTEND ---
  frontend:
    build: ./frontend
    container_name: sgd-frontend-v1
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - sgd-network
      
volumes:
  pg_discografia_data:
  minio_storage_data:

networks:
  sgd-network:
    driver: bridge