-- Criação da tabela de Artistas
CREATE TABLE artist (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
                        updated_at TIMESTAMP WITHOUT TIME ZONE
);

-- Criação da tabela de Álbuns
CREATE TABLE album (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       artist_id BIGINT NOT NULL,
                       created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
                       updated_at TIMESTAMP WITHOUT TIME ZONE,

                       CONSTRAINT fk_album_artist FOREIGN KEY (artist_id) REFERENCES artist(id) ON DELETE CASCADE
);

-- Criação da tabela de Imagens do Álbum
CREATE TABLE album_image (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             album_id BIGINT NOT NULL,
                             file_key VARCHAR(500) NOT NULL,
                             file_name VARCHAR(255),
                             content_type VARCHAR(100),
                             created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),

                             CONSTRAINT fk_image_album FOREIGN KEY (album_id) REFERENCES album(id) ON DELETE CASCADE
);

CREATE INDEX idx_artist_name ON artist(name);
CREATE INDEX idx_album_title ON album(title);
CREATE INDEX idx_album_artist_id ON album(artist_id);