CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       login VARCHAR(100) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL DEFAULT 'USER',
                       created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

INSERT INTO users (login, password, role)
VALUES ('admin', '$2a$12$P2.wA5/tZ2JqXy1qGv.zFO/nO2/wJ.uz.c.y.g.w.r.t.y.u.i.o', 'ADMIN');