CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       login VARCHAR(100) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL DEFAULT 'USER',
                       created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

INSERT INTO users (login, password, role)
VALUES ('admin', '$2a$10$51ze7IbDXska5CQmz9SKFu/Scncz9YitJd7QygmGVcwbqfnBPw6Cm', 'ADMIN');