-- Criação da tabela de Sincronização com Sistemas Externos
CREATE TABLE syncs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_external VARCHAR(255) NOT NULL UNIQUE,
    entity_type VARCHAR(100) NOT NULL,
    entity_id BIGINT NOT NULL,
    external_data TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    last_sync_at TIMESTAMP WITHOUT TIME ZONE,
    sync_error_message TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

-- Índices para melhor performance
CREATE INDEX idx_syncs_id_external ON syncs(id_external);
CREATE INDEX idx_syncs_entity_type ON syncs(entity_type);
CREATE INDEX idx_syncs_entity_id ON syncs(entity_id);
CREATE INDEX idx_syncs_status ON syncs(status);
CREATE INDEX idx_syncs_created_at ON syncs(created_at);
